/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_market_MainActivity_LableDetectionTask */

#ifndef _Included_com_example_market_MainActivity_LableDetectionTask
#define _Included_com_example_market_MainActivity_LableDetectionTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
