/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_market_MainActivity_loadImageTask */

#ifndef _Included_com_example_market_MainActivity_loadImageTask
#define _Included_com_example_market_MainActivity_loadImageTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
