/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_market_MainActivity_Crolling */

#ifndef _Included_com_example_market_MainActivity_Crolling
#define _Included_com_example_market_MainActivity_Crolling
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
